services:
  sync-server:
    image: ghcr.io/strangebytesorg/sync-server:latest
    ports:
      - 31700:31700
    environment:
      - PASSWORD=${PASSWORD}
      - DATA_DIR=/data
    volumes:
      - ./sync-data:/data
