name: Build and Push Docker Image

on:
  push:
    tags: ['v*']

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Compress Linux Binary
        run: tar -cJf sync-server-x64.tar.gz sync-server
        
      - name: Build and upload Binary
        run: bun run build

      - name: Upload Github Release Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.tar.gz
